const abi = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "batchId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "productData",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiryDate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum AdvancedSupplyChain.StorageCondition",
        name: "storageCondition",
        type: "uint8",
      },
    ],
    name: "BatchCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "batchId",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "quantityTransferred",
        type: "uint256",
      },
    ],
    name: "BatchTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "enum AdvancedSupplyChain.Role",
        name: "role",
        type: "uint8",
      },
    ],
    name: "RoleAssigned",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "_user", type: "address" },
      {
        internalType: "enum AdvancedSupplyChain.Role",
        name: "_role",
        type: "uint8",
      },
    ],
    name: "assignRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "batchQuantities",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "batches",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "productData", type: "string" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint256", name: "quantity", type: "uint256" },
      { internalType: "uint256", name: "quantityTransferred", type: "uint256" },
      { internalType: "uint256", name: "expiryDate", type: "uint256" },
      {
        internalType: "enum AdvancedSupplyChain.StorageCondition",
        name: "storageCondition",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_productData", type: "string" },
      { internalType: "uint256", name: "_quantity", type: "uint256" },
      { internalType: "uint256", name: "_expiryDate", type: "uint256" },
      {
        internalType: "enum AdvancedSupplyChain.StorageCondition",
        name: "_storageCondition",
        type: "uint8",
      },
    ],
    name: "createBatch",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllBatches",
    outputs: [
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "string[]", name: "", type: "string[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "address[]", name: "", type: "address[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      {
        internalType: "enum AdvancedSupplyChain.StorageCondition[]",
        name: "",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_batchId", type: "uint256" }],
    name: "getBatchDetails",
    outputs: [
      { internalType: "string", name: "productData", type: "string" },
      { internalType: "uint256", name: "quantity", type: "uint256" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "address[]", name: "chainOfCustody", type: "address[]" },
      {
        components: [
          { internalType: "address", name: "from", type: "address" },
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint256", name: "quantity", type: "uint256" },
          {
            internalType: "enum AdvancedSupplyChain.Role",
            name: "fromRole",
            type: "uint8",
          },
          {
            internalType: "enum AdvancedSupplyChain.Role",
            name: "toRole",
            type: "uint8",
          },
        ],
        internalType: "struct AdvancedSupplyChain.Transfer[]",
        name: "transfers",
        type: "tuple[]",
      },
      { internalType: "uint256", name: "expiryDate", type: "uint256" },
      {
        internalType: "enum AdvancedSupplyChain.StorageCondition",
        name: "storageCondition",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getBatchesByAddress",
    outputs: [
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getTransfersByAddress",
    outputs: [
      { internalType: "uint256[]", name: "batchIds", type: "uint256[]" },
      { internalType: "address[]", name: "fromAddresses", type: "address[]" },
      { internalType: "address[]", name: "toAddresses", type: "address[]" },
      { internalType: "uint256[]", name: "quantities", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "getUserRole",
    outputs: [
      {
        internalType: "enum AdvancedSupplyChain.Role",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "isRegistered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_user", type: "address" }],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_batchIds", type: "uint256[]" },
      { internalType: "address", name: "_recipient", type: "address" },
      { internalType: "uint256[]", name: "_quantities", type: "uint256[]" },
    ],
    name: "transferBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userRoles",
    outputs: [
      {
        internalType: "enum AdvancedSupplyChain.Role",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export default abi;
